name = "looking-for-the-future"
main = "src/worker.js"
compatibility_date = "2026-07-22"

[assets]
directory = "dist"
binding = "STATIC"
run_worker_first = true

[[kv_namespaces]]
binding = "JOB_ACTIONS_KV"
id = "96639890e4e545abab540692eda0d433"
